[book]
chinese_name = "千子"
english_name = "A Thousand Sons"
type = "长篇小说"
series.name = "Horus Heresy"
series.order = 12
authors = ["Graham McNeill"]
recommended_reading = []
faction_keywords = ["千子", "太空野狼", "怀言者", "圣血天使", "帝皇之子", "死亡守卫", "白色伤疤", "禁军", "混沌恶魔", "寂静修女"]
