[book]
chinese_name = "福格瑞姆"
english_name = "Fulgrim"
type = "长篇小说"
series.name = "Horus Heresy"
series.order = 5
authors = ["Graham McNeill"]
recommended_reading = ["艾森斯坦号的逃亡"]
faction_keywords = ["帝皇之子", "钢铁之手", "怀言者", "方舟灵族", "混沌恶魔", "火蜥蜴", "暗鸦守卫"]
