packages:
  - depage
  - web-cmp-translate
  - turndown

catalog:
  '@nanoseeds/wh40k-icon': ^0.3.1
  '@types/node': ^22.17.0
  '@vitejs/plugin-vue': ^6.0.1
  archiver: 7.0.1
  density-clustering: 1.3.0
  jsdom: 26.1.0
  markdown-it-footnote: 4.0.0
  ollama: 0.5.16
  openai: 5.11.0
  pako: 2.1.0
  pinyin-pro: 3.26.0
  turndown: 7.2.0
  vite: 7.0.6
  vitepress: 1.6.3
  vue: 3.5.18
  zlib: 1.0.5
