packages:
  - depage
  - web-cmp-translate
  - turndown

catalog:
  '@astrojs/sitemap': ^3.3.0
  '@nanoseeds/wh40k-icon': ^0.4.1
  '@types/node': ^22.19.10
  '@vitejs/plugin-vue': ^6.0.1
  astro: ^5.12.3
  cytoscape: ^3.33.1
  cytoscape-dagre: ^2.5.0
  dagre: ^0.8.5
  density-clustering: 1.3.0
  jsdom: 26.1.0
  ollama: 0.5.16
  openai: 5.12.2
  pako: 2.1.0
  pinyin-pro: 3.27.0
  remark-footnotes: ^4.0.0
  tar: ^7.5.9
  turndown: 7.2.0
  vite: 7.3.1
  vue: 3.5.18
  zlib: 1.0.5

supportedArchitectures:
  cpu: [x64]
  os: [win32, linux]
