[book]
chinese_name = "普罗斯佩罗之焚"
english_name = "Prospero Burns"
type = "长篇小说"
series.name = "Horus Heresy"
series.order = 15
authors = ["Dan Abnett"]
recommended_reading = ["千子"]
faction_keywords = ["千子", "太空野狼", "寂静修女会"]
