[book]
chinese_name = "破碎军团"
english_name = "Shattered Legions"
type = "短篇小说集"
series.name = "Horus Heresy"
series.order = 43
authors = ["Laurie Goulding"]

[[sub]]
chinese_name = "美杜森"
english_name = "Meduson"
type = "短篇小说"
authors = ["Dan Abnett"]

[[sub]]
chinese_name = "未锻造的"
english_name = "Unforged"
type = "短篇小说"
authors = ["Guy Haley"]

[[sub]]
chinese_name = "未铸之钢"
english_name = "Unforged-2"
type = "短篇小说"
authors = ["Nick Kyme"]

[[sub]]
chinese_name = "不朽的职责"
english_name = "Immortal Duty"
type = "短篇小说"
authors = ["Nick Kyme"]

[[sub]]
chinese_name = "灰爪号"
english_name = "Grey Talon"
type = "短篇小说"
authors = [" Chris Wraight"]

[[sub]]
chinese_name = "赫尔之钥"
english_name = "The Keys of Hel"
type = "短篇小说"
authors = ["John French"]

[[sub]]
chinese_name = "行为不朽"
english_name = "Deeds Endure"
type = "短篇小说"
authors = ["Gav Thorpe"]

[[sub]]
chinese_name = "绞索"
english_name = "The Noose"
type = "短篇小说"
authors = ["David Annandale"]

[[sub]]
chinese_name = "未说出的"
english_name = "Unspoken"
type = "短篇小说"
authors = ["Guy Haley"]

[[sub]]
chinese_name = "第七条蛇"
english_name = "The Seventh Serpent"
type = "中篇小说"
authors = ["Graham McNeill"]

[[sub]]
chinese_name = "手选"
english_name = "The Hand Elect"
type = "短篇小说"
authors = ["Chris Wraight"]

[[sub]]
chinese_name = "亦者"
english_name = "The Either"
type = "短篇小说"
authors = ["Graham McNeill"]
