[book]
chinese_name = "不被铭记的帝国"
english_name = "The Unremembered Empire"
type = "长篇小说"
series.name = "Horus Heresy"
series.order = 27
authors = ["Dan Abnett"]
recommended_reading = [
    "惧于踏足",
    { name = "考斯印记"},
    { enname = "The Crimson Fist", belongto = { name = "背叛之影", series = { name = "Horus Heresy", order = 22 } } },
    { enname = "Iron Within", belongto = { enname = "Age of Darkness", series = { name = "Horus Heresy", order = 16 } } },
    "伏尔甘永存",
]
