[book]
chinese_name = "科拉克斯-不再"
english_name = "Corax-Nevermore"
type = "短篇小说集"
series.name = "Horus Heresy"
series.order = 40
authors = ["Gav Thorpe"]


[[sub]]
chinese_name = "科拉克斯"
english_name = "Corax"
type = "短篇小说"
authors = ["Gav Thorpe"]
factory_keywords = ["暗鸦守卫", "太空野狼", "吞世者", "叛变泰坦军团", "叛变骑士家族", "千子", "阿尔法军团"]


[[sub]]
chinese_name = "灵魂熔炉"
english_name = "Soulforge"
type = "中篇小说"
authors = ["Gav Thorpe"]
factory_keywords = ["暗鸦守卫", "怀言者", "机械教", "黑暗机械教"]
recommended_reading = [
    "失落救赎",
    { name = "暗影大师", belongto = { name = "科拉克斯-不再", series = { name = "Horus Heresy", order = 40 } } },
]

[[sub]]
chinese_name = "暗影大师"
english_name = "The shadowmasters"
type = "短篇小说"
authors = ["Gav Thorpe"]
factory_keywords = ["暗鸦守卫", "黑暗机械教"]
recommended_reading = []

[[sub]]
chinese_name = "暗鸦之主"
english_name = "Ravenlord"
type = "中篇小说"
authors = ["Gav Thorpe"]
factory_keywords = ["暗鸦守卫", "破碎军团", "怀言者", "帝皇之子", "荷鲁斯之子", "黑暗机械教"]
recommended_reading = [
    { name = "灵魂熔炉", belongto = { name = "科拉克斯-不再", series = { name = "Horus Heresy", order = 40 } } },
]

[[sub]]
chinese_name = "恐惧的价值"
english_name = "The Value of Fear"
type = "短篇小说"
authors = ["Gav Thorpe"]
factory_keywords = ["暗鸦守卫", "阿尔法军团", "午夜领主"]
recommended_reading = [
    { name = "暗鸦之主", belongto = { name = "科拉克斯-不再", series = { name = "Horus Heresy", order = 40 } } },
]

[[sub]]
chinese_name = "猛禽"
english_name = "Raptor"
type = "短篇小说"
authors = ["Gav Thorpe"]
factory_keywords = ["暗鸦守卫", "荷鲁斯之子", "太空野狼"]
recommended_reading = ["失落救赎"]

[[sub]]
chinese_name = "死亡之债"
english_name = "Weregeld"
type = "中篇小说"
authors = ["Gav Thorpe"]
recommended_reading = [
    "狼毒",
    { name = "恐惧的价值", belongto = { name = "科拉克斯-不再", series = { name = "Horus Heresy", order = 40 } } },
]
