[book]
chinese_name = "塔兰"
english_name = "The Silent War"
type = "短篇小说集"
series.name = "Horus Heresy"
series.order = 45
authors = ["John French"]

[[sub]]
chinese_name = "塔兰-见证者"
english_name = "Tallarn Witness"
type = "短篇小说"
authors = ["John French"]
recommended_reading = [
    { name = "塔兰-处决者", belongto = { name = "塔兰", series = { name = "Horus Heresy", order = 45 } } },
]
faction_keywords = ["帝国卫队"]

[[sub]]
chinese_name = "塔兰-处决者"
english_name = "Tallarn Executioner"
type = "中篇小说"
authors = ["John French"]
recommended_reading = [
    { name = "黑暗之眼", belongto = { name = "无尽的战争", series = { name = "Horus Heresy", order = 33 } } },
]
faction_keywords = ["帝国卫队", "钢铁之手", "叛变泰坦军团", "阿尔法军团", "白色伤疤", "帝国之拳", "暗黑天使"]

[[sub]]
chinese_name = "塔兰-警报器"
english_name = "Tallarn Siren"
type = "短篇小说"
authors = ["John French"]
recommended_reading = [
    { name = "塔兰-处决者", belongto = { name = "塔兰", series = { name = "Horus Heresy", order = 45 } } },
]
faction_keywords = ["帝国卫队", "帝国之拳", "钢铁勇士"]

[[sub]]
chinese_name = "塔兰-铁甲"
english_name = "Tallarn Ironclad"
type = "中篇小说"
authors = ["John French"]
recommended_reading = [
    { name = "鹰之爪", belongto = { name = "泰拉之眼", series = { name = "Horus Heresy", order = 35 } } },
    { name = "塔兰-见证者", belongto = { name = "塔兰", series = { name = "Horus Heresy", order = 45 } } },
    { name = "塔兰-警报器", belongto = { name = "塔兰", series = { name = "Horus Heresy", order = 45 } } },
    { name = "黑暗顺从", belongto = { name = "围城先驱", series = { name = "Horus Heresy", order = 52 } } },
]
faction_keywords = ["帝国卫队", "刺客庭", "黑暗机械教", "钢铁勇士", "荷鲁斯之子", "钢铁之手", "阿尔法军团"]
