[book]
chinese_name = "围城先驱"
english_name = "Heralds of the Siege"
type = "短篇小说集"
series.name = "Horus Heresy"
series.order = 52
authors = ["Nick Kyme", "Laruie Goulding"]

[[sub]]
chinese_name = "万变"
english_name = "Myriad"
type = "短篇小说"
authors = ["Rob Sanders"]
faction_keywords = ["机械教", "泰坦军团", "黑暗机械教"]
recommended_reading = [
    { name = "憎恶智能", belongto = { name = "忠诚的负担", series = { name = "Horus Heresy", order = 48 } } },
]

[[sub]]
chinese_name = "灰鸦"
english_name = "The Grey Raven"
type = "短篇小说"
authors = ["Gav Thorpe"]
faction_keywords = ["禁军", "暗鸦守卫", "帝国之拳", "游侠骑士"]
recommended_reading = [
    { name = "死亡之债", belongto = { name = "科拉克斯", series = { name = "Horus Heresy", order = 40 } } },
]

[[sub]]
chinese_name = "瓦莱里乌斯"
english_name = "Valerius"
type = "短篇小说"
authors = ["Gav Thorpe"]
faction_keywords = ["帝国卫队", "荷鲁斯之子", "叛变泰坦军团"]
recommended_reading = [
    { name = "死亡之债", belongto = { name = "科拉克斯", series = { name = "Horus Heresy", order = 40 } } },
]

[[sub]]
chinese_name = "灰烬狼群"
english_name = "The Ember Wolves"
type = "短篇小说"
authors = ["Rob Sanders"]
faction_keywords = ["泰坦军团", "叛变泰坦军团"]

[[sub]]
chinese_name = "黑盾"
english_name = "Blackshield"
type = "短篇小说"
authors = ["Chris Wraight"]
faction_keywords = ["死亡守卫", "破碎军团"]
recommended_reading = ["复仇之魂"]

[[sub]]
chinese_name = "魔域子民"
english_name = "Children of Sicarus"
type = "短篇小说"
authors = ["Anthony Reynolds"]
faction_keywords = ["怀言者", "混沌教派"]
recommended_reading = ["无所畏惧"]

[[sub]]
chinese_name = "胞吐"
english_name = "Exocytosis"
type = "短篇小说"
authors = ["James Swallow"]
faction_keywords = ["死亡守卫", "混沌教派", "暗黑天使", "堕天使"]
recommended_reading = ["卡利班天使"]

[[sub]]
chinese_name = "纹面伯爵"
english_name = "The Painted Count"
type = "短篇小说"
authors = ["Guy Haley"]
faction_keywords = ["午夜领主", "混沌恶魔"]
recommended_reading = ["法洛斯"]

[[sub]]
chinese_name = "普罗斯佩罗的最后之子"
english_name = "The Last Son of Prospero"
type = "短篇小说"
authors = ["Chris Wraight"]
faction_keywords = ["千子", "白色伤疤"]
recommended_reading=["天堂之路"]

[[sub]]
chinese_name = "割魂者"
english_name = "The Soul, Severed"
type = "短篇小说"
authors = ["Chris Wraight"]
faction_keywords = ["帝皇之子"]
recommended_reading=["天堂之路"]

[[sub]]
chinese_name = "黑暗顺从"
english_name = "Dark Compliance"
type = "短篇小说"
authors = ["John French"]

[[sub]]
chinese_name = "职责等待"
english_name = "Duty Waits"
type = "短篇小说"
authors = ["Guy Haley"]

[[sub]]
chinese_name = "教诲权"
english_name = "Magisterium"
type = "短篇小说"
authors = ["Chris Wraight"]

[[sub]]
chinese_name = "午夜将至"
english_name = "Now Peals Midnight"
type = "短篇小说"
authors = ["John French"]

[[sub]]
chinese_name = "统一之梦"
english_name = "Dreams of Unity"
type = "短篇小说"
authors = ["Nick Kyme"]

[[sub]]
chinese_name = "棋局已定"
english_name = "The Board is Set"
type = "短篇小说"
authors = ["Gav Thorpe"]
