[book]
chinese_name = "宿敌"
english_name = "Nemesis"
type = "长篇小说"
series.name = "Horus Heresy"
series.order = 13
authors = ["James Swallow"]
recommended_reading = []
faction_keywords = ["刺客庭", "荷鲁斯之子", "混沌恶魔"]
