[book]
chinese_name = "荷鲁斯崛起"
english_name = "Horus Rising"
type = "长篇小说"
series.name = "Horus Heresy"
series.order = 1
authors = ["Dan Abnett"]
recommended_reading = []
faction_keywords = ["荷鲁斯之子", "帝皇之子", "混沌恶魔"]
