[book]
chinese_name = "无声战争"
english_name = "The Silent War"
type = "短篇小说集"
series.name = "Horus Heresy"
series.order = 37
authors = [
    "Anthony Reynolds",
    "Christian Dunn",
    "Chris Wraight",
    "Graham McNeill",
    "James Swallow",
    "John French",
    "Nick Kyme",
    "Rob Sanders",
]


[[sub]]
chinese_name = "肃清"
english_name = "The Purge"
type = "中篇小说"
authors = ["Anthony Reynolds"]
factory_keywords = ["极限战士", "怀言者", "混沌恶魔"]
recommended_reading = [
    "无所畏惧",
    { name = "风暴之嗣", belongto = { name = "异端传说", series = { name = "Horus Heresy", order = 10 } } },
]

[[sub]]
chinese_name = "掌印者"
english_name = "The Sigillite"
type = "短篇小说"
authors = ["Chris Wraight"]
recommended_reading = ["福格瑞姆"]

[[sub]]
chinese_name = "狼猎"
english_name = "Wolf Hunt"
type = "短篇小说"
authors = ["Graham McNeill"]

[[sub]]
chinese_name = "一人成军"
english_name = "Army of One"
type = "短篇小说"
authors = ["Rob Sanders"]
factory_keywords = ["刺客庭"]
recommended_reading = ["福格瑞姆"]

[[sub]]
chinese_name = "泰拉之门"
english_name = "The Gates of Terra"
type = "短篇小说"
authors = ["Nick Kyme"]

[[sub]]
chinese_name = "幽魂不语"
english_name = "Ghosts Speak Not"
type = "短篇小说"
authors = ["James Swallow"]
recommended_reading = [
    { name = "声音", belongto = { name = "异端传说", series = { name = "Horus Heresy", order = 10 } } },
    { name = "最后的记述者", belongto = { name = "黑暗时代", series = { name = "Horus Heresy", order = 16 } } },
]

[[sub]]
chinese_name = "圣殿骑士"
english_name = "Templar"
type = "短篇小说"
authors = ["John French"]
recommended_reading = [
    { name = "绯红之拳", belongto = { name = "背叛之影", series = { name = "Horus Heresy", order = 22 } } },
    { name = "肃清", belongto = { name = "无声战争", series = { name = "Horus Heresy", order = 37 } } },
]

[[sub]]
chinese_name = "长夜回响"
english_name = "Distant Echoes of Old Night"
type = "短篇小说"
authors = ["Rob Sanders"]
recommended_reading = [
    "燃烧的银河"
]
faction_keywords = ["死亡守卫", "帝国之拳", "游侠骑士"]

[[sub]]
chinese_name = "灰天使"
english_name = "Grey Angel"
type = "短篇小说"
authors = ["John French"]
recommended_reading = [
    { name = "影月虚影", belongto = { name = "无声战争", series = { name = "Horus Heresy", order = 37 } } },
]

[[sub]]
chinese_name = "失落之子"
english_name = "Lost Sons"
type = "短篇小说"
authors = ["James Swallow"]
recommended_reading = [
    "惧于踏足"
]
faction_keywords = ["圣血天使", "游侠骑士"]

[[sub]]
chinese_name = "夜之子"
english_name = "Child of Night"
type = "短篇小说"
authors = ["John French"]
recommended_reading = ["福格瑞姆"]
faction_keywords = ["午夜领主", "游侠骑士"]

[[sub]]
chinese_name = "影月虚影"
english_name = "Luna Mendax"
type = "短篇小说"
authors = ["Graham McNeill"]
recommended_reading = [
    { name = "灰天使", belongto = { name = "无声战争", series = { name = "Horus Heresy", order = 37 } } }
]
faction_keywords = ["荷鲁斯之子", "游侠骑士"]

[[sub]]
chinese_name = "耐心"
english_name = "PATIENCE"
type = "短篇小说"
authors = ["James Swallow"]
factory_keywords = ["游侠骑士", "混沌恶魔"]
recommended_reading = [
    { name = "幽魂不语", belongto = { name = "无声战争", series = { name = "Horus Heresy", order = 37 } } },
]

[[sub]]
chinese_name = "守望者"
english_name = "The Watcher"
type = "短篇小说"
authors = ["Christian Dunn"]
factory_keywords = ["游侠骑士", "太空野狼", "午夜领主"]
recommended_reading = []