[book]
chinese_name = "泰拉之眼"
english_name = "Eye of Terra"
type = "短篇小说集"
series.name = "Horus Heresy"
series.order = 35
authors = [
    "Aaron Dembski-Bowden",
    "Andy Smillie",
    "Chris Wraight",
    "David Annandale",
    "Gav Thorpe",
    "Graham McNeill",
    "Guy Haley",
    "John French",
    "Matthew Farrer",
    "Nick Kyme",
    "Rob Sanders",
]

[[sub]]
chinese_name = "焚尘之狼"
english_name = "The Wolf of Ash and Fire"
type = "短篇小说"
authors = ["Graham McNeill"]
recommended_reading = ["荷鲁斯崛起"]
faction_keywords = ["影月苍狼", "禁军"]

[[sub]]
chinese_name = "奥瑞利安"
english_name = "Aurelian"
type = "中篇小说"
authors = ["Aaron Dembski-Bowden"]
recommended_reading = [
    { name = "异端之首", series = { name = "Horus Heresy", order = 14 } },
]
faction_keywords = ["怀言者", "千子"]

[[sub]]
chinese_name = "大屠杀"
english_name = "Massacre"
type = "短篇小说"
authors = ["Aaron Dembski-Bowden"]
recommended_reading = ["福格瑞姆"]
faction_keywords = ["午夜领主"]

[[sub]]
chinese_name = "月之兄弟会"
english_name = "Brotherhood of the Moon"
type = "短篇小说"
authors = ["Chris Wraight"]
recommended_reading = [
    { enname = "Scars", series = { name = "Horus Heresy", order = 28 } },
]
faction_keywords = ["白色伤疤", "荷鲁斯之子"]

[[sub]]
chinese_name = "继承者"
english_name = "Inheritor"
type = "短篇小说"
authors = ["Gav Thorpe"]
recommended_reading = [
    { name = "背叛者", series = { name = "Horus Heresy", order = 24 } },
]
faction_keywords = ["怀言者", "吞世者", "极限战士"]

[[sub]]
chinese_name = "沃拉克斯"
english_name = "Vorax"
type = "短篇小说"
authors = ["Matthew Farrer"]
recommended_reading = ["机械教", "福格瑞姆"]
faction_keywords = ["机械教"]

[[sub]]
chinese_name = "炎铁"
english_name = "Ironfire"
type = "短篇小说"
authors = ["Rob Sanders"]
recommended_reading = [
    { name = "钢铁本质", belongto = { name = "黑暗时代", series = { name = "Horus Heresy", order = 16 } } },
]
faction_keywords = ["钢铁勇士", "帝皇之子"]

[[sub]]
chinese_name = "钢铁之火"
english_name = "Ironfire 2"
type = "短篇小说"
authors = ["Rob Sanders"]
recommended_reading = [
    { name = "钢铁本质", belongto = { name = "黑暗时代", series = { name = "Horus Heresy", order = 16 } } },
]
faction_keywords = ["钢铁勇士", "帝皇之子"]

[[sub]]
chinese_name = "红印"
english_name = "Red-Marked"
type = "短篇小说"
authors = ["Nick Kyme"]
recommended_reading = [
    { name = "谴责", belongto = { name = "背叛之遗", series = { name = "Horus Heresy", order = 31 } } },
]
faction_keywords = ["极限战士", "怀言者", "吞世者"]

[[sub]]
chinese_name = "第一战团长"
english_name = "Master of the First"
type = "短篇小说"
authors = ["Gav Thorpe"]
recommended_reading = [
    { name = "群鸦王子", belongto = { name = "背叛之影", series = { name = "Horus Heresy", order = 22 } } },
]
faction_keywords = ["暗黑天使"]

[[sub]]
chinese_name = "首席导师"
english_name = "Master of the First v2"
type = "短篇小说"
authors = ["Gav Thorpe"]
recommended_reading = [
    { name = "群鸦王子", belongto = { name = "背叛之影", series = { name = "Horus Heresy", order = 22 } } },
]
faction_keywords = ["暗黑天使"]

[[sub]]
chinese_name = "策略"
english_name = "Stratagem"
type = "短篇小说"
authors = ["Nick Kyme"]
recommended_reading = [
    { name = "红印", belongto = { name = "泰拉之眼", series = { name = "Horus Heresy", order = 35 } } },
    "不被铭记的帝国",
]
faction_keywords = ["极限战士"]

[[sub]]
chinese_name = "长夜"
english_name = "The Long Night"
type = "短篇小说"
authors = ["Aaron Dembski-Bowden"]
recommended_reading = [
    { name = "群鸦王子", belongto = { name = "背叛之影", series = { name = "Horus Heresy", order = 22 } } },
]
faction_keywords = ["午夜领主", "暗黑天使"]

[[sub]]
chinese_name = "父之罪孽"
english_name = "Sins of the Father"
type = "短篇小说"
authors = ["Andy Smillie"]
recommended_reading = [
    { name = "子嗣所长", belongto = { name = "无尽的战争", series = { name = "Horus Heresy", order = 33 } } },
]
faction_keywords = ["圣血天使"]

[[sub]]
chinese_name = "鹰之爪"
english_name = "The Eagle's Talon"
type = "短篇小说"
authors = ["John French"]
faction_keywords = ["帝国之拳", "钢铁勇士"]

[[sub]]
chinese_name = "钢铁尸体"
english_name = "Iron Corpses"
type = "短篇小说"
authors = ["David Annandale"]
faction_keywords = ["钢铁勇士", "泰坦军团"]

[[sub]]
chinese_name = "63-14世界的最终归顺"
english_name = "The Final Compliance of 63-14"
type = "短篇小说"
authors = ["Guy Haley"]
faction_keywords = ["荷鲁斯之子"]

[[sub]]
chinese_name = "圣吉列斯的传令官"
english_name = "Herald of Sanguinius"
type = "短篇小说"
authors = ["Andy Smillie"]
recommended_reading = [
    { name = "父之罪孽", belongto = { name = "泰拉之眼", series = { name = "Horus Heresy", order = 35 } } },
]
faction_keywords = ["圣血天使"]

[[sub]]
chinese_name = "圣吉列斯先躯"
english_name = "Herald of Sanguinius v2"
type = "短篇小说"
authors = ["Andy Smillie"]
recommended_reading = [
    { name = "父之罪孽", belongto = { name = "泰拉之眼", series = { name = "Horus Heresy", order = 35 } } },
]
faction_keywords = ["圣血天使"]

