name: binary

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: certseeds/common-actions/actions/checkout@v1

      - name: Set up Go
        uses: certseeds/common-actions/actions/setup-go@v1
        with:
          cache-dependency-path: goserver/go.mod

      - name: copy files to main folder
        run: |
          tree

      - name: Run GoReleaser
        uses: certseeds/common-actions/actions/build-go-binary@v1
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --skip=publish --clean --snapshot --verbose
          workdir: goserver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: certseeds/common-actions/actions/upload-artifact@v1
        with:
          name: goserver
          path: goserver/dist/*